Repository LOVDnl/LOVD3, pull requests merged in 2021-09, with the labels that each got.

#549 Several fixes to the APIs.
  src/api.php
  src/class/api.ga4gh.php
Labels: bug minor, cat: API

#551 Define Genome_builds table
  src/inc-init.php
  src/install/inc-sql-tables.php
Labels: cat: core, cat: installer

#552 Have genome builds table created, and data viewable
  src/.htaccess
  src/class/object_genome_builds.php
  src/genome_builds.php
  src/inc-init.php
  src/inc-lib-init.php
  src/inc-upgrade.php
Labels: cat: core, cat: installer

#554 Fix XSS
  src/class/objects.php
  src/class/template.php
  src/genes.php
  src/inc-lib-form.php
  src/inc-lib-init.php
  src/individuals.php
  src/phenotypes.php
  src/screenings.php
  src/scripts/convert_lovd2.php
  src/users.php
  src/variants.php
Labels: bug critical, cat: interface

#555 Fix lovd_checkXSS().
  src/class/object_diseases.php
  src/class/object_genome_variants.php
  src/class/object_individuals.php
  src/class/object_phenotypes.php
  src/class/object_screenings.php
  src/class/object_system_settings.php
  src/class/object_transcript_variants.php
  src/class/object_transcripts.php
  src/class/object_users.php
  src/inc-lib-form.php
Labels: bug minor

#556 Gb/enable
  src/genome_builds.php
  src/inc-init.php
  src/inc-lib-form.php
  src/inc-lib-init.php
  src/inc-upgrade.php
Labels: cat: interface, cat: genome builds
